# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a873c16434a61db2e97ad405ba009e87e08640613892bd1eb1fad26183c8dccaea573efec4d4e214c534fdbbc055b330edf1615b4774d9b032e1eefbad6409c

test:
  secret_key_base: 7f9edbda08e60be565eeecaa9397b14af61b32ad2e1e8346189f74e0380ed5fb084043b460191aae176aefa23fc533e7a4baa639f534477da51e2faa94da1bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
